### ISSUE TITLE
Add Feedly to track CLs tweets

### ISSUE THREAD

**Issue by ajeetraina** [docker-community-leaders/alphasite#6]
It would be great to keep track of what CLs are tweeting via Feedly.

**Comment by sangam14** [comment]
https://docker-community-leaders.github.io/alphasite/feedly/

**Comment by ajeetraina** [comment]
Thanks. I just created a new Docker Community Leaders Twitter account https://twitter.com/dockercommunity and then created a list. Modified a new feedly.

**Comment by sangam14** [comment]
lets close this !
